version: "3"
services:
  ecommerce-db:
    container_name: ecommerce-db
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./init/setup-database.sql:/docker-entrypoint-initdb.d/setup-database.sql
      - mysql:/var/lib/mysql
    restart: on-failure
    networks:
      - enet

  ecommerce-backend:
    container_name: ecommerce-backend
    image: kritikasingh6421/ecommerce-backend:v1
    ports:
      - "8082:8082"
    # links:
    #   - ecommerce-db
    environment:
      SPRING_PROFILES_ACTIVE: docker
      # DB_HOST: ecommerce-db
      # DB_PORT: 3306
      # DB_NAME: ecommerce
      # DB_USERNAME: root
      # DB_PASSWORD: root
    depends_on:
      - ecommerce-db
    volumes:
      - ecommerce-data:/wockspace/data
    restart: on-failure
    networks:
      - enet

  ecommerce-frontend:
    container_name: ecommerce-frontend
    image: kritikasingh6421/ecommerce-frontend:v2
    ports:
      - "4200:4200"
    depends_on:
      - ecommerce-backend
    links:
      - ecommerce-backend
    volumes:
      - ecommerce-data:/wockspace/data
    restart: always
    networks:
      - enet

networks:
  enet:

volumes:
  ecommerce-data:
  mysql:
